// Generated by CoffeeScript 1.3.3
(function() {

  define(['chai', 'app'], function(chai) {
    return describe('App Initialization', function() {
      return describe('When the app object is required', function() {
        return it('should return an angular module', function() {
          var app;
          app = require('app');
          return chai.expect(app).to.exist;
        });
      });
    });
  });

}).call(this);
