// Generated by CoffeeScript 1.3.3
(function() {

  define(['app/scripts/app'], function() {
    return describe("When initializing the app", function() {
      var app;
      app = require("app/scripts/app");
      return it("should be defined", function() {
        return expect(app).toBeDefined();
      });
    });
  });

}).call(this);
